class TaskError(Exception):
    """タスクの処理中に発生したエラー"""

################################################################
# 処理ごとのエラー
################################################################

class DBError(TaskError):
    """データベース関連のエラー"""
